server {
    listen 80;
    # Aquí agregas tu nombre de dominio
    server_name asesor-at&t.com www.asesor-at&t.com;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Importante para React Router: redirigir rutas al index.html
        try_files $uri $uri/ /index.html;
    }
}